### ISSUE TITLE
Feature Request: exclude from sitemap with frontmatter

### ISSUE THREAD

**Issue by brianmercer** [ekoeryanto/vuepress-plugin-sitemap#18]
Please consider adding a method to exclude pages from the sitemap through a frontmatter tag. i.e.

```
---
Title: Page That I Don't Want In the Sitemap
sitemap: false
---
```

**Comment by hi-kato** [comment]
This is nice idea.

Since I want to exclude "404. html", I would like to propose another method.

## In proposal
### add to Options
I thought it would be nice to add 「exclude」 to Options.
```js
exclude:
  type: array
  required: false
  default: []
  example: 
    exclude:[
        '/404.html',
        '/hoge/'
    ]
```

 ### Modify index.js
1. Add option(exclude) as follows in [this part](https://github.com/ekoeryanto/vuepress-plugin-sitemap/blob/0030d5cd632ab8bb11ccc0eb88b87ca255923a70/index.js#L15-L24) 
    ```diff
      const {
        urls = [],
        hostname,
        cacheTime = 600,
        xslUrl,
        xmlNs,
        outFile = 'sitemap.xml',
        changefreq = 'daily',
    +   exclude = [],
        ...others
      } = options
    ```
1. Modify [this part](https://github.com/ekoeryanto/vuepress-plugin-sitemap/blob/0030d5cd632ab8bb11ccc0eb88b87ca255923a70/index.js#L79) as follows

    ```diff
      pagesMap.forEach((page, url) => {
    -   sitemap.add({ url, ...page })
    +   if (!exclude.includes(url)) sitemap.add({ url, ...page })
      })
    ```

**Comment by ekoeryanto** [comment]
@hi-kato hit a PR, please

**Comment by dsturm** [comment]
Hey @ekoeryanto, would you please release a new version (to npm) for this new feature?

**Comment by ekoeryanto** [comment]
done
